import { useState, useMemo } from 'react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, ReferenceLine } from 'recharts'
import { stateData, nationalStats } from '../../data/syntheticStates'

function ValueLayer() {
  const [scope, setScope] = useState('National')
  const [currentAdoption, setCurrentAdoption] = useState(12)
  const [targetAdoption, setTargetAdoption] = useState(25)
  const [population, setPopulation] = useState(nationalStats.totalEligible)
  const [prevalence, setPrevalence] = useState(parseFloat(nationalStats.avgPrevalence))
  const [payerMix, setPayerMix] = useState({ commercial: 55, medicare: 35, medicaid: 10 })

  const handleScopeChange = (newScope) => {
    setScope(newScope)
    if (newScope === 'National') {
      setPopulation(nationalStats.totalEligible)
      setPrevalence(parseFloat(nationalStats.avgPrevalence))
      setCurrentAdoption(nationalStats.avgAdoption)
    } else {
      const state = stateData.find(s => s.state_name === newScope)
      if (state) {
        setPopulation(state.eligible_population)
        setPrevalence(state.prevalence_rate)
        setCurrentAdoption(state.adoption_score)
      }
    }
  }

  const calculations = useMemo(() => {
    const atRiskPopulation = population * (prevalence / 100)
    const currentScreened = atRiskPopulation * (currentAdoption / 100)
    const targetScreened = atRiskPopulation * (targetAdoption / 100)
    const additionalScreened = targetScreened - currentScreened

    const riskReclassificationRate = 0.25
    const maceReductionRate = 0.30
    const baselineMaceRate = 0.08

    const costPerScan = 150
    const costPerMaceEvent = 35000
    const qalyValuePerEvent = 0.3

    const patientsReclassified = additionalScreened * riskReclassificationRate
    const potentialMaceEvents = additionalScreened * baselineMaceRate
    const eventsPrevented = potentialMaceEvents * maceReductionRate

    const implementationCost = additionalScreened * costPerScan
    const savingsFromEventsPrevented = eventsPrevented * costPerMaceEvent
    const netSavings = savingsFromEventsPrevented - implementationCost
    const roi = implementationCost > 0 ? savingsFromEventsPrevented / implementationCost : 0
    const qalysSaved = eventsPrevented * qalyValuePerEvent

    return {
      livesImpacted: Math.round(additionalScreened),
      eventsPrevented: Math.round(eventsPrevented),
      totalSavings: Math.round(savingsFromEventsPrevented),
      implementationCost: Math.round(implementationCost),
      netSavings: Math.round(netSavings),
      roi: roi.toFixed(2),
      qalys: Math.round(qalysSaved * 10) / 10,
      currentBurden: Math.round(atRiskPopulation * baselineMaceRate * costPerMaceEvent)
    }
  }, [population, prevalence, currentAdoption, targetAdoption])

  const chartData = [
    { name: 'Current Burden', value: calculations.currentBurden / 1000000, fill: '#9BAABB' },
    { name: 'Implementation Cost', value: -calculations.implementationCost / 1000000, fill: '#6B7280' },
    { name: 'Events Prevented', value: calculations.totalSavings / 1000000, fill: '#C8102E' },
    { name: 'Net Savings', value: calculations.netSavings / 1000000, fill: '#1A1A1A' },
  ]

  const formatCurrency = (value) => {
    if (Math.abs(value) >= 1000000000) return `$${(value / 1000000000).toFixed(1)}B`
    if (Math.abs(value) >= 1000000) return `$${(value / 1000000).toFixed(1)}M`
    if (Math.abs(value) >= 1000) return `$${(value / 1000).toFixed(0)}K`
    return `$${value.toLocaleString()}`
  }

  const handleDownloadAssumptions = () => {
    const assumptions = `
CARDIOVASCULAR PREVENTION INDEX - ESVA CALCULATOR ASSUMPTIONS
============================================================

GEOGRAPHIC SCOPE: ${scope}
Current Adoption Rate: ${currentAdoption}%
Target Adoption Rate: ${targetAdoption}%
Eligible Population: ${population.toLocaleString()}
Disease Prevalence: ${prevalence}%

PAYER MIX:
- Commercial: ${payerMix.commercial}%
- Medicare: ${payerMix.medicare}%
- Medicaid: ${payerMix.medicaid}%

KEY ASSUMPTIONS:
- Risk reclassification rate: 25% (based on MESA study)
- MACE reduction rate with appropriate treatment: 30%
- Baseline 10-year MACE rate for intermediate risk: 8%
- Average cost per CAC scan: $150
- Average cost per MACE event: $35,000
- QALYs saved per event prevented: 0.3

CALCULATED OUTPUTS:
- Lives Impacted: ${calculations.livesImpacted.toLocaleString()}
- MACE Events Prevented: ${calculations.eventsPrevented.toLocaleString()}
- Total Cost Savings: ${formatCurrency(calculations.totalSavings)}
- Implementation Cost: ${formatCurrency(calculations.implementationCost)}
- Net Savings: ${formatCurrency(calculations.netSavings)}
- ROI Ratio: ${calculations.roi}x
- QALYs Gained: ${calculations.qalys}

---
Generated by Cardiovascular Prevention Index
American Heart Association
For demonstration purposes only - synthetic data
    `.trim()

    alert(assumptions)
  }

  const inputStyle = {
    border: '1px solid #E5E7EB',
    borderRadius: '6px',
    padding: '10px 14px',
    fontSize: '14px',
    color: '#1A1A1A',
    outline: 'none',
    width: '100%',
    backgroundColor: 'white'
  }

  const labelStyle = { fontSize: '13px', fontWeight: '500', color: '#1A1A1A', marginBottom: '6px', display: 'block' }

  return (
    <div className="space-y-12">
      {/* Section Header */}
      <div>
        <h2 className="text-2xl font-bold mb-3" style={{ color: '#1A1A1A' }}>What's the value of closing the gap?</h2>
        <div style={{ height: '3px', width: '48px', backgroundColor: '#C8102E', marginBottom: '16px' }}></div>
        <p style={{ color: '#6B7280' }}>Economic and social value analysis of increasing CAC scoring adoption</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Input Controls */}
        <div className="bg-white rounded-lg p-8 space-y-7" style={{ border: '1px solid #E5E7EB', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' }}>
          <h3 className="font-semibold text-base" style={{ color: '#1A1A1A' }}>Model Parameters</h3>

          {/* Geographic Scope */}
          <div>
            <label style={labelStyle}>Geographic Scope</label>
            <select
              value={scope}
              onChange={(e) => handleScopeChange(e.target.value)}
              style={inputStyle}
            >
              <option value="National">National</option>
              {stateData.map(state => (
                <option key={state.state_code} value={state.state_name}>{state.state_name}</option>
              ))}
            </select>
          </div>

          {/* Current Adoption Rate */}
          <div>
            <label style={labelStyle}>
              Current Adoption Rate:{' '}
              <span style={{ color: '#C8102E', fontWeight: '700' }}>{currentAdoption}%</span>
            </label>
            <input
              type="range"
              min="0"
              max="40"
              value={currentAdoption}
              onChange={(e) => setCurrentAdoption(parseInt(e.target.value))}
              className="w-full"
            />
            <div className="flex justify-between text-xs mt-1" style={{ color: '#9BAABB' }}>
              <span>0%</span>
              <span>40%</span>
            </div>
          </div>

          {/* Target Adoption Rate */}
          <div>
            <label style={labelStyle}>
              Target Adoption Rate:{' '}
              <span style={{ color: '#1A7A4A', fontWeight: '700' }}>{targetAdoption}%</span>
            </label>
            <input
              type="range"
              min="0"
              max="60"
              value={targetAdoption}
              onChange={(e) => setTargetAdoption(parseInt(e.target.value))}
              className="w-full"
            />
            <div className="flex justify-between text-xs mt-1" style={{ color: '#9BAABB' }}>
              <span>0%</span>
              <span>60%</span>
            </div>
          </div>

          {/* Population & Prevalence */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label style={labelStyle}>Eligible Population</label>
              <input
                type="number"
                value={population}
                onChange={(e) => setPopulation(parseInt(e.target.value) || 0)}
                style={inputStyle}
              />
            </div>
            <div>
              <label style={labelStyle}>CVD Prevalence (%)</label>
              <input
                type="number"
                step="0.1"
                value={prevalence}
                onChange={(e) => setPrevalence(parseFloat(e.target.value) || 0)}
                style={inputStyle}
              />
            </div>
          </div>

          {/* Payer Mix */}
          <div>
            <label style={{ ...labelStyle, marginBottom: '12px' }}>Payer Mix</label>
            <div className="space-y-4">
              {[
                { key: 'commercial', label: 'Commercial', color: '#C8102E' },
                { key: 'medicare', label: 'Medicare', color: '#1A1A1A' }
              ].map(({ key, label, color }) => (
                <div key={key}>
                  <div className="flex justify-between text-sm mb-1">
                    <span style={{ color: '#6B7280' }}>{label}</span>
                    <span className="font-semibold" style={{ color: '#1A1A1A' }}>{payerMix[key]}%</span>
                  </div>
                  <input
                    type="range"
                    min="0"
                    max={key === 'medicare' ? 100 - payerMix.commercial : 100}
                    value={payerMix[key]}
                    onChange={(e) => {
                      const val = parseInt(e.target.value)
                      if (key === 'commercial') {
                        const remaining = 100 - val
                        setPayerMix({ commercial: val, medicare: Math.min(payerMix.medicare, remaining), medicaid: remaining - Math.min(payerMix.medicare, remaining) })
                      } else {
                        setPayerMix({ ...payerMix, medicare: val, medicaid: 100 - payerMix.commercial - val })
                      }
                    }}
                    className="w-full"
                  />
                </div>
              ))}
              <div>
                <div className="flex justify-between text-sm mb-1">
                  <span style={{ color: '#6B7280' }}>Medicaid</span>
                  <span className="font-semibold" style={{ color: '#1A1A1A' }}>{payerMix.medicaid}%</span>
                </div>
                <div className="w-full rounded-full" style={{ height: '6px', backgroundColor: '#E5E7EB' }}>
                  <div
                    className="rounded-full"
                    style={{ height: '6px', width: `${payerMix.medicaid}%`, backgroundColor: '#9BAABB' }}
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Output Results */}
        <div className="space-y-4">
          {/* Key Metrics Grid */}
          <div className="grid grid-cols-2 gap-4">
            {[
              { label: 'Lives Impacted', value: calculations.livesImpacted.toLocaleString(), color: '#1A1A1A' },
              { label: 'MACE Events Prevented', value: calculations.eventsPrevented.toLocaleString(), color: '#C8102E' },
              { label: 'Total Cost Savings', value: formatCurrency(calculations.totalSavings), color: '#1A7A4A' },
              { label: 'Implementation Cost', value: formatCurrency(calculations.implementationCost), color: '#6B7280' },
              { label: 'ROI Ratio', value: `${calculations.roi}x`, color: '#C8102E' },
              { label: 'QALYs Gained', value: calculations.qalys.toLocaleString(), color: '#1A1A1A' }
            ].map((metric, i) => (
              <div
                key={i}
                className="bg-white rounded-lg p-6"
                style={{ border: '1px solid #E5E7EB', boxShadow: '0 1px 4px rgba(0,0,0,0.05)' }}
              >
                <div className="text-xs mb-2" style={{ color: '#6B7280' }}>{metric.label}</div>
                <div className="text-2xl font-bold" style={{ color: metric.color }}>{metric.value}</div>
              </div>
            ))}
          </div>

          {/* Net Savings Highlight */}
          <div
            className="rounded-lg p-7"
            style={{
              backgroundColor: calculations.netSavings >= 0 ? '#E8F5EE' : '#FEF0EE',
              border: `1px solid ${calculations.netSavings >= 0 ? '#A8DFC0' : '#F5C6C0'}`
            }}
          >
            <div className="text-sm mb-2" style={{ color: '#6B7280' }}>Net Savings</div>
            <div
              className="text-4xl font-bold mb-3"
              style={{ color: calculations.netSavings >= 0 ? '#1A7A4A' : '#C0392B' }}
            >
              {formatCurrency(calculations.netSavings)}
            </div>
            <p className="text-sm leading-relaxed" style={{ color: '#6B7280' }}>
              {calculations.netSavings >= 0
                ? `For every dollar invested, ${calculations.roi}x is returned through prevented cardiac events.`
                : 'Implementation cost exceeds projected savings at current parameters.'}
            </p>
          </div>
        </div>
      </div>

      {/* Chart Section */}
      <div className="bg-white rounded-lg p-8" style={{ border: '1px solid #E5E7EB', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' }}>
        <h3 className="font-semibold mb-7" style={{ color: '#1A1A1A' }}>Value Flow Analysis</h3>
        <div style={{ height: '300px' }}>
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={chartData} layout="vertical" margin={{ top: 5, right: 30, left: 130, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" horizontal={true} vertical={false} stroke="#F3F4F6" />
              <XAxis
                type="number"
                tickFormatter={(v) => `$${v}M`}
                domain={['auto', 'auto']}
                tick={{ fill: '#9BAABB', fontSize: 12 }}
                axisLine={{ stroke: '#E5E7EB' }}
              />
              <YAxis
                type="category"
                dataKey="name"
                tick={{ fill: '#1A1A1A', fontSize: 12, fontWeight: 500 }}
                width={120}
                axisLine={false}
                tickLine={false}
              />
              <Tooltip
                formatter={(value) => [`$${Math.abs(value).toFixed(1)}M`, '']}
                contentStyle={{ borderRadius: '6px', border: '1px solid #E5E7EB', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }}
                labelStyle={{ color: '#1A1A1A', fontWeight: 600 }}
              />
              <ReferenceLine x={0} stroke="#E5E7EB" />
              <Bar dataKey="value" radius={[0, 4, 4, 0]}>
                {chartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.fill} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Download Button */}
      <div className="flex justify-center">
        <button
          onClick={handleDownloadAssumptions}
          className="inline-flex items-center px-6 py-3 rounded font-medium text-sm transition-colors"
          style={{ backgroundColor: '#F8F8F8', color: '#1A1A1A', border: '1px solid #E5E7EB' }}
          onMouseEnter={e => { e.currentTarget.style.backgroundColor = '#E5E7EB' }}
          onMouseLeave={e => { e.currentTarget.style.backgroundColor = '#F8F8F8' }}
        >
          <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download Assumptions
        </button>
      </div>

      {/* Methodology Note */}
      <div className="rounded-lg p-8" style={{ backgroundColor: '#F8F8F8', border: '1px solid #E5E7EB' }}>
        <h4 className="font-semibold mb-4" style={{ color: '#1A1A1A' }}>Methodology Notes</h4>
        <ul className="space-y-2 text-sm list-disc list-inside" style={{ color: '#6B7280' }}>
          <li>Risk reclassification rate (25%) based on MESA and CAC Consortium studies</li>
          <li>MACE reduction (30%) assumes appropriate treatment of reclassified patients</li>
          <li>Baseline MACE rate (8% 10-year) reflects intermediate-risk population</li>
          <li>All figures are synthetic and for demonstration purposes only</li>
          <li>Actual implementation would require health plan claims data integration</li>
        </ul>
      </div>
    </div>
  )
}

export default ValueLayer
